steps:

- id: 'Compilando a aplicação'
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'calculadora']
  env: ['GOPATH=.']

- id: 'Executando o teste unitário'
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '-v', './...']
  env: ['GOPATH=.']

- id: 'Executando aplicação'
  name: "gcr.io/cloud-builders/go"
  args: ['run', 'calculadora']
  env: ['GOPATH=.']

- id: 'Registrando a imagem'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/calculadora:latest'
    - '.'

images:
  - 'gcr.io/$PROJECT_ID/calculadora:latest'
