steps:

- id: 'Compilando a aplicação'
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'calculadora']
  env: ['GOPATH=.']

- id: 'Executar o teste unitário'
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '-v', './...']
  env: ['GOPATH=.']
